name: python-predictor-docker-pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd predictor
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Docker build
        run: |
          cd predictor
          docker build -t malaria-predictor-test .

  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./predictor
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/malaria-predictor:latest
